stages:
    - Build
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

build-image:
    stage: Build
    only:
        - develop
        - main
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind

    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --pull -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
